### PR TITLE
Hero background image

### PR DESCRIPTION
**Pull request by nikolas-ball**
Screen Shot 2021-10-31 at 5 50 07 PM

### CODE REVIEW

**Comment by LAKEx** [comment]
One minor thing. Can the white outline of the logo be vertical on both sides of the text? The small crease on the right is bugging me.

**Comment by LAKEx** [comment]
On the buttons, what about a dropshadow? The white border feels a little strange

**Comment by nikolas-ball** [comment]
thoughts?:
Screen Shot 2021-11-01 at 1 11 49 PM

**Comment by nikolas-ball** [comment]
moved changes to https://github.com/websummittech/WebSummit/pull/7

**Pull request closed without merging**
